version: "3.9" 
services:
  web:
    build: .
    ports:
      - "23880:3000"
    volumes:
      - ./src:/app/src
      - logvolume:/var/log
    command: npm run start
    env_file: .env
    links:
      - redis
  redis:
    image: redis:6.2.6-alpine
volumes:
  logvolume: {}