version: "3.9" 
services:
  web:
    build: .
    ports:
      - "23780:3000"
    volumes:
      - ./src:/app/src
      - logvolume:/var/log
    command: npm run debug
    env_file: .env
  redis:
    image: redis:6.2.6-alpine
volumes:
  logvolume: {}